owner: tuyencaovn
repo: recruituptime

sites:
  - name: Recruit Connect - Web
    url: https://recruitconnect.vn
  - name: Recruit Connect - Admin
    url: https://admin.recruitconnect.vn
  - name: Recruit Connect - API
    url: https://api.recruitconnect.vn

status-website:
  cname: all.webuptime2023.online
  name: Recruite Connect Status
i18n:
  footer: © Tuyen Cao 2023 | All rights reserved
